### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by cuthberts** [nzjs/Automated-Survey123-Reports#2]
Hi,

I'm getting the following error when I try to run the python script in IDLE v3.5.2
![image](https://user-images.githubusercontent.com/8953510/94093046-98600800-fe5f-11ea-8273-6aebcc46eeb1.png)

Any advice would be great.

Cheers

**Comment by nzjs** [comment]
Hi, you probably need to install the `requests` lib in your environment. 

Try one of these, then run the main script
`pip install requests` or
`python -m pip install requests`

You may also need to pip install these libs: smtplib, python-docx, glob

**Comment by cuthberts** [comment]
Cheers John
